apiVersion: apps/v1
kind: Deployment
metadata:
  name: breast-cancer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breast-cancer-api
  template:
    metadata:
      labels:
        app: breast-cancer-api
    spec:
      containers:
      - name: breast-cancer-api
        image: breast-cancer-api:latest
        ports:
        - containerPort: 8000